// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: peso_esp32_hx711

#ifndef _PESO_ESP32_HX711_UI_H
#define _PESO_ESP32_HX711_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_restart;
extern lv_obj_t * ui_mostrarip;
extern lv_obj_t * ui_mostrarpeso;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Image2;
// CUSTOM VARIABLES
extern lv_obj_t * uic_restar_peso;
extern lv_obj_t * uic_mostrar_ip;
extern lv_obj_t * uic_mostar_peso;

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_itmv2_png);    // assets/itmv2.png

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
