// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: peso_esp32_hx711

#include "ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_restart = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_restart, 208);
    lv_obj_set_height(ui_restart, 213);
    lv_obj_set_x(ui_restart, 270);
    lv_obj_set_y(ui_restart, -24);
    lv_obj_set_align(ui_restart, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_restart, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_restart, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_restart, 100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_mostrarip = lv_textarea_create(ui_Screen1);
    lv_obj_set_width(ui_mostrarip, 209);
    lv_obj_set_height(ui_mostrarip, 56);
    lv_obj_set_x(ui_mostrarip, -284);
    lv_obj_set_y(ui_mostrarip, -197);
    lv_obj_set_align(ui_mostrarip, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_mostrarip, "Placeholder...");



    ui_mostrarpeso = lv_textarea_create(ui_Screen1);
    lv_obj_set_width(ui_mostrarpeso, 357);
    lv_obj_set_height(ui_mostrarpeso, 84);
    lv_obj_set_x(ui_mostrarpeso, -65);
    lv_obj_set_y(ui_mostrarpeso, -6);
    lv_obj_set_align(ui_mostrarpeso, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_mostrarpeso, "Placeholder...");
    lv_obj_set_style_text_font(ui_mostrarpeso, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_Label1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, 271);
    lv_obj_set_y(ui_Label1, -30);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "reset");
    lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, -201);
    lv_obj_set_y(ui_Label2, -61);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "PESO");

    ui_Label4 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, 259);
    lv_obj_set_y(ui_Label4, -195);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "Cristian Cardona\nDeyvid Ramirez");

    ui_Image2 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image2, &ui_img_itmv2_png);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image2, 2);
    lv_obj_set_y(ui_Image2, 190);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    uic_restar_peso = ui_restart;
    uic_mostrar_ip = ui_mostrarip;
    uic_mostar_peso = ui_mostrarpeso;

}
